# Site wide configuration

title:            Esta couve flor
locale:           pt_BR
url:              https://www.estacouveflor.com

# Jekyll configuration

permalink:        /:categories/:title/
markdown:         kramdown
highlighter:      rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site owner
owner:
  name: Cleiton Loiola
  avatar: https://github.com/klaygomes.png
  bio: Software design is an art, and like any art it cannot be taught and learned as precise science, by means of theorems and formulas.
  github: klaygomes
  stackoverflow: 136258/cleiton
  facebook: klaygomes
  disqus-shortname: estacouveflor
  linkedin: klaygomes

# Site includes

include: 
  - .htaccess
exclude: 
  - lib
  - config.rb
  - config
  - log
  - tmp
  - less
  - test
  - spec
  - Gruntfile.js
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - Gruntfile.js
  - CNAME
